name: cloudcompare 
base: core18
version: '2.11' 
summary: 3D point cloud and mesh processing software
description: |
  CloudCompare is a 3D point cloud (and triangular mesh) processing software.
  Originally designed to perform comparison between two dense 3D points clouds
  or between a point cloud and a triangular mesh, it has been extended to a
  more generic point cloud processing software, including many advanced
  algorithms (registration, resampling, color/normal/scalar fields handling,
  statistics computation, sensor management, interactive or automatic
  segmentation, display enhancement, etc.).
type: app
icon: snap/gui/cloudcompare.png
license: GPL-3.0
grade: stable
confinement: strict
architectures:
  - build-on: amd64 # only amd64 for now
    run-on: amd64 # only amd64 for now

plugs:
  # Support for common GTK themes
  # https://forum.snapcraft.io/t/how-to-use-the-system-gtk-theme-via-the-gtk-common-themes-snap/6235
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes

apps:
  ccViewer:
    command: bin/desktop-launch ccViewer
    # $SNAP_ARCH_TRIPLET doesn't seems to be substitued in environment, so it's hardcoded for now
    environment:
      QT_QPA_PLATFORMTHEME: "gtk3"
      LD_LIBRARY_PATH: "$SNAP/lib/cloudcompare:$SNAP/usr/lib/x86_64-linux-gnu/blas:$SNAP/usr/lib/x86_64-linux-gnu/lapack:$LD_LIBRARY_PATH"
      DISABLE_WAYLAND: "1"
    plugs: [desktop, desktop-legacy, home, x11, wayland, unity7, opengl, removable-media]
  CloudCompare:
    command: bin/desktop-launch CloudCompare
    environment:
      QT_QPA_PLATFORMTHEME: "gtk3"
      LD_LIBRARY_PATH: "$SNAP/lib/cloudcompare:$SNAP/usr/lib/x86_64-linux-gnu/blas:$SNAP/usr/lib/x86_64-linux-gnu/lapack:$LD_LIBRARY_PATH"
      DISABLE_WAYLAND: "1"
    plugs: [desktop, desktop-legacy, home, x11, wayland, unity7, opengl, removable-media]

parts:
  cloudcompare:
    after: [eigen, pdal, desktop-qt5]
    plugin: cmake
    source: .
    source: https://github.com/CloudCompare/CloudCompare.git
    source-type: git
    source-depth: 10
    source-branch: v2.11.x
    build-packages:
      - build-essential
      - libavcodec-dev
      - libavformat-dev
      - libavutil-dev
      - libboost-thread-dev
      - libboost-program-options-dev
      - libcgal-dev
      - libcgal-qt5-dev
      - libdlib-dev
      - libjsoncpp-dev
      - libswscale-dev
      - libtbb-dev
      - libgdal-dev
      - libxerces-c-dev
      - libpcl-dev
      - libproj-dev
      - libqt5svg5-dev
    stage-packages:
      - libaec0
      - libarmadillo8
      - libarpack2
      - libdap25
      - libdapclient6v5
      - libepsilon1
      - libfreexl1
      - libfyba0
      - libgdal20
      - libgeos-3.6.2
      - libgeos-c1v5
      - libgeotiff2
      - libgfortran4
      - libgif7
      - libhdf4-0-alt
      - libhdf5-100
      - libkmlbase1
      - libkmldom1
      - libkmlengine1
      - libnetcdf13
      - libogdi3.2
      - libpoppler73
      - libproj12
      - libqhull7
      - libquadmath0
      - libspatialite7
      - libsuperlu5
      - libsz2
      - libtbb2
      - liburiparser1
      - libxerces-c3.2
      - odbcinst1debian2
      - libboost-chrono1.65.1
      - libglu1-mesa
      - libqt5concurrent5
      - libqt5opengl5
      - libqt5printsupport5
      - qtwayland5
      - qt5-gtk-platformtheme # see gtk plugs

# PCL deps
      - libboost-filesystem1.65.1
      - libboost-iostreams1.65.1
      - libboost-system1.65.1
      - libboost-thread1.65.1
      - libflann1.9
      - libhwloc5
      - libjsoncpp1
      - libnetcdf-c++4
      - libopenmpi2
      - libopenni0
      - libopenni2-0
      - libpcl-common1.8
      - libpcl-features1.8
      - libpcl-filters1.8
      - libpcl-io1.8
      - libpcl-kdtree1.8
      - libpcl-ml1.8
      - libpcl-octree1.8
      - libpcl-recognition1.8
      - libpcl-sample-consensus1.8
      - libpcl-search1.8
      - libpcl-segmentation1.8
      - libpcl-surface1.8
      - libtinyxml2.6.2v5
      - libvtk6.3

    configflags:
      - -DCMAKE_BUILD_TYPE=Release
# CCLib
      - -DCOMPILE_CC_CORE_LIB_WITH_CGAL=ON
      - -DCOMPILE_CC_CORE_LIB_WITH_TBB=ON
# File Format
      - -DOPTION_USE_GDAL=ON
      - -DOPTION_USE_DXF_LIB=ON
      - -DOPTION_USE_SHAPE_LIB=ON
# plugins
  # Shaders
      - -DPLUGIN_GL_QEDL=ON
      - -DPLUGIN_GL_QSSAO=ON
  # Hidden Points Removal
      - -DPLUGIN_STANDARD_QHPR=ON
  # PCV (AO from point cloud)
      - -DPLUGIN_STANDARD_QPCV=ON
  # Additional IO
      - -DPLUGIN_IO_QPDAL=ON
      - -DPLUGIN_IO_QE57=ON
      - -DPLUGIN_IO_QADDITIONAL=ON
      - -DPLUGIN_IO_QCORE=ON
  # Poisson recon
  # Need to set SNAPCRAFT_BUILD_ENVIRONMENT_MEMORY=4G
      - -DPLUGIN_STANDARD_QPOISSON_RECON=ON
      - -DPOISSON_RECON_WITH_OPEN_MP=ON
  # Animation (screen cast)
      - -DPLUGIN_STANDARD_QANIMATION=ON
      - -DWITH_FFMPEG_SUPPORT=ON
      - -DFFMPEG_INCLUDE_DIR=/usr/include/x86_64-linux-gnu
      - -DFFMPEG_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu
  # Surface Revolution Analysis
      - -DPLUGIN_STANDARD_QSRA=ON
  # Cloth Simulation Filter (from MNS to MNT)
      - -DPLUGIN_STANDARD_QCSF=ON
  # Experimental Photoscan import
      - -DPLUGIN_IO_QPHOTOSCAN=ON
  # Facets (Extracts planar facets from a PC)
      - -DPLUGIN_STANDARD_QFACETS=ON
  # Broom (clean your PCs - the fun way)
      - -DPLUGIN_STANDARD_QBROOM=ON
  # Hough Normals (robust normal computation for unstructured PCs)
      - -DPLUGIN_STANDARD_QHOUGH_NORMALS=ON
      - -DEIGEN_ROOT_DIR=/usr/include/eigen3
  # Compass (Geological toolbox)
      - -DPLUGIN_STANDARD_QCOMPASS=ON
  # M3C2 (Robust C2C Computation)
      - -DPLUGIN_STANDARD_QM3C2=ON
  # Canupo (Classify PCs with SVM)
      - -DPLUGIN_STANDARD_QCANUPO=ON
      - -DDLIB_ROOT=/usr/include
  # PCL (use Point Cloud Library with CC PCs)
      - -DPLUGIN_STANDARD_QPCL=ON
  eigen:
    plugin: cmake
    source: https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.bz2
    build-packages:
      - build-essential
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
  laszip:
    plugin: cmake
    source: https://github.com/LASzip/LASzip.git
    source-type: git
    source-tag: "3.4.3"
    build-packages:
      - build-essential
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
  pdal:
    after: [laszip, eigen]
    plugin: cmake
    source: https://github.com/PDAL/PDAL.git
    source-type: git
    source-tag: "2.0.1"
    # ! no stage-packages since gdal dynamic library are installed via the main "CloudCompare" part
    build-packages:
      - build-essential
      - libgdal-dev
      - libgeotiff-dev
      - libjsoncpp-dev
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DWITH_TESTS=OFF
      - -DWITH_LASZIP=ON
      - -DBUILD_PLUGIN_PYTHON=OFF
      - -DBUILD_PLUGIN_PGPOINTCLOUD=OFF
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5
